# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      # Only allow Python 3.9.x versions
      - dependency-name: "python"
        versions: ["3.9.*"]
    ignore:
      - dependency-name: "python"
        versions: [">= 3.10"]  # Block Python 3.10
