name: PR Text Check

on:
  push:
    branches:
      - 'main'    
jobs:
  check-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        #with:
          #fetch-depth: 0  # Fetch full history to compare branches

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

          #git diff origin/${{ github.base_ref }} origin/${{ github.head_ref }} > diff.txt
          #if grep -q "FROM.*" diff.txt; then
            #echo "Found 'FROM Directive' in changes."
            #exit 1
          #fi
