name: Print Context
on: push

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context values
        run: |
          echo "Main Branch: ${{ github.base_ref }}"
          echo "Feature Branch: ${{ github.head_ref }}"
