name: Print Context
on: push

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context values
        run: |
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Actor: ${{ github.actor }}"
