name: Print Context
on: [pull_request]

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context values
        run: |
          echo "Branch: ${{ github.head_ref }}"
          echo "Actor: ${{ github.actor }}"
