name: Print Context
on: push

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context values
        run: |
          echo "Branch: ${{ github.base_ref }}"
          echo "Actor: ${{ github.actor }}"
